# Generated by Django 5.2.11 on 2026-02-26 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('enrollment_success', 'Enrollment Berhasil'), ('payment_success', 'Pembayaran Berhasil'), ('payment_failed', 'Pembayaran Gagal'), ('new_lesson', 'Materi Baru'), ('new_quiz', 'Quiz/Tugas Baru'), ('deadline_reminder', 'Pengingat Deadline'), ('progress_milestone', 'Pencapaian Progress'), ('certificate_issued', 'Sertifikat Diterbitkan'), ('instructor_announcement', 'Pengumuman dari Pengajar'), ('new_review', 'Review Baru pada Course-mu'), ('submission_received', 'Ada Submission Tugas Baru')], max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Penting')], default='medium', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_543da6_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_8ddc07_idx'), models.Index(fields=['notif_type', 'priority'], name='notificatio_notif_t_38ecfb_idx')],
            },
        ),
    ]
