# Generated by Django 5.2.11 on 2026-02-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('enrollment_success', 'Enrollment Berhasil'), ('payment_success', 'Pembayaran Berhasil'), ('payment_failed', 'Pembayaran Gagal'), ('new_lesson', 'Materi Baru'), ('new_quiz', 'Quiz/Tugas Baru'), ('deadline_reminder', 'Pengingat Deadline'), ('progress_milestone', 'Pencapaian Progress'), ('certificate_issued', 'Sertifikat Diterbitkan'), ('instructor_announcement', 'Pengumuman dari Pengajar'), ('new_review', 'Review Baru pada Course-mu'), ('submission_received', 'Submission Reviewed')], max_length=40),
        ),
    ]
